"use client";
import React from "react";
import { useGetSalesQuery } from "@/app/features/api/salesApi";
import { Table, Skeleton } from "antd";
import Print from "@/app/utils/Print";

const SalesReport = () => {
  const { data, isLoading } = useGetSalesQuery();

  if (isLoading) {
    return <Skeleton active />;
  }

  const sales = data?.data || [];
  const pagination = data?.pagination || {};

  // Table columns
  const columns = [
    {
      title: "Date",
      dataIndex: "createdAt",
      key: "createdAt",
      render: (date) => new Date(date).toLocaleString(),
    },
    {
      title: "Customer Name",
      dataIndex: ["customer", "firstName"],
      key: "customerName",
    },
    {
      title: "Customer Email",
      dataIndex: ["customer", "email"],
      key: "customerEmail",
    },
    {
      title: "Variant",
      dataIndex: ["variant", "value"],
      key: "variant",
    },
    { title: "Quantity", dataIndex: "quantity", key: "quantity" },
    { title: "Unit Price", dataIndex: "unitPrice", key: "unitPrice" },
    { title: "Sales Price", dataIndex: "salesPrice", key: "salesPrice" },
    {
      title: "Discount",
      key: "discount",
      render: (_, record) => (
        <span>
          {record.discountType}: {record.discountAmount}
        </span>
      ),
    },
    {
      title: "Tax",
      key: "tax",
      render: (_, record) => (
        <span>
          {record.taxType}: {record.tax}
        </span>
      ),
    },
    {
      title: "Final Amount",
      dataIndex: "finalAmount",
      key: "finalAmount",
      render: (value) => (
        <span style={{ fontWeight: "bold", color: "green" }}>{value}</span>
      ),
    },
  ];

  // invoiceData build from sales
  const invoiceData = {
    brandName: "Selo Pos",
    tagline: "Smart Sales Reporting",
    date: new Date().toLocaleDateString(),
    invoiceNumber: "SR-" + new Date().getTime(),
    items: sales.map((row, index) => ({
      sl: index + 1,
      date: new Date(row.createdAt).toLocaleString(),
      name: row?.customer?.firstName || "-",
      email: row?.customer?.email || "-",
      variant: row?.variant?.value || "-",
      quantity: row?.quantity ?? 0,
      unitPrice: row?.unitPrice ?? 0,
      salesPrice: row?.salesPrice ?? 0,
      discount: row?.discountType
        ? `${row.discountType}: ${row.discountAmount}`
        : "-",
      tax: row?.taxType ? `${row.taxType}: ${row.tax}` : "-",
      finalAmount: row?.finalAmount ?? 0,
    })),

    terms: "This report is auto-generated by the system.",
  };

  return (
    <div className="p-4">
      <h2 className="text-xl font-semibold mb-4">Sales Report</h2>
      <Print invoiceData={invoiceData} salesReport />

      <Table
        columns={columns}
        dataSource={sales}
        rowKey="id"
        bordered
        pagination={{
          current: pagination.page,
          pageSize: pagination.limit,
          total: pagination.total,
        }}
        scroll={{ x: "max-content" }}
      />
    </div>
  );
};

export default SalesReport;
